services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=project-place'
      - 'POSTGRES_PASSWORD=project-place'
      - 'POSTGRES_USER=project-place'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: project-place-backend
    build: .
    command: ./gradlew bootRun
    depends_on:
      - postgres
    environment:
      JWT_SECRET: 8448660aa6fa3a070f7a2008874ecda08642b5bb3fcdcb0de3b80da6596eaa5eb966c8dd4c0338d5c0662b9db0ff7f69d1aa3aa0091dcee96cc5e01416ca8351
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/project-place
      SPRING_DATASOURCE_USERNAME: project-place
      SPRING_DATASOURCE_PASSWORD: project-place
    ports:
      - '8080:8080'
    volumes:
      - .:/app
    working_dir: /app

volumes:
  postgres_data: