spring:
  application:
    name: project-place-backend
  datasource:
    driver-class-name: org.postgresql.Driver
    password: project-place
    username: project-place
    url: jdbc:postgresql://localhost:5432/project-place
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect