spring:
  application:
    name: project-place-backend
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD:project-place}
    username: ${DB_USERNAME:project-place}
    url: jdbc:postgresql://localhost:5432/project-place
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
  docker:
    compose:
      lifecycle-management: start-only
error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR
springdoc:
  paths-to-match: /api/**
  enable-spring-security: true

app:
  superadmin:
    username: ${ADMIN_USERNAME:superadmin}
    password: ${ADMIN_PASSWORD:superadmin}