spring:
  application:
    name: project-place-backend
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD:project-place}
    username: ${DB_USERNAME:project-place}
    url: jdbc:postgresql://localhost:5432/project-place
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    open-in-view: false

app:
  superadmin:
    username: ${ADMIN_USERNAME:superadmin}
    password: ${ADMIN_PASSWORD:superadmin}